import BootstrapClient from "@/componenets/libraries/bootstrap";
import "./globals.css";
import Header from "@/componenets/layout/Header";
import ToastifyClient from "@/componenets/libraries/ToastifyClient";
import Footer from "@/componenets/layout/Footer";
import NextNprogress from "@/componenets/libraries/next-nprogress";
import { AuthProvider } from "@/context/AuthContext";
import Providers from "@/redux/Provider";

export const metadata = {
  title: "Online Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <AuthProvider>
          <Providers>
            <NextNprogress>
              <Header />

              {children}

              <Footer />

              <BootstrapClient />
              <ToastifyClient />
            </NextNprogress>
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
